/**
 * Template CSS Generators — AUTO-GENERATED
 *
 * Generated by scripts/generate_template_css.js from template_styles_output.json.
 * Each template has a generator function that outputs hardcoded CSS for all elements.
 *
 * DO NOT EDIT MANUALLY — re-run the generator script to update.
 */

/**
 * Helper: determine element index within a template instantiation.
 * Elements are rendered in document order — we track which index this element is
 * by storing a counter on the element's fromTemplate + type sequence.
 */
const elementIndexMap = new WeakMap();
let currentTemplateCounters = {};
let currentTemplateId = null;

export function resetTemplateCounters() {
  currentTemplateCounters = {};
  currentTemplateId = null;
}

function getElementIndex(element) {
  if (elementIndexMap.has(element)) return elementIndexMap.get(element);

  const templateId = element.fromTemplate;
  if (templateId !== currentTemplateId) {
    currentTemplateCounters = {};
    currentTemplateId = templateId;
  }

  if (currentTemplateCounters[templateId] === undefined) {
    currentTemplateCounters[templateId] = 0;
  }

  const idx = currentTemplateCounters[templateId]++;
  elementIndexMap.set(element, idx);
  return idx;
}

const generate_announcement_bar_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        max-width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
        gap: 12px;
        padding-left: 20px;
        padding-right: 20px;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [1] container > text // "Free shipping on all orders ov"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1;
        display: block;
        letter-spacing: 0.5px;
        text-align: center;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [2] container > button // "Shop Now"
    if (elementIndex === 2) {
      css += `${selector} {
        border-radius: 3px;
        cursor: pointer;
        display: inline-block;
        letter-spacing: 0.5px;
        padding-top: 6px;
        padding-right: 16px;
        padding-bottom: 6px;
        padding-left: 16px;
        border-width: 1px;
        border-style: solid;
      }
`;
    }

  return css;
};

const generate_before_after_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > heading // "See the Difference"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1.2;
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [3] container > columns-2 > col-0 > image
    if (elementIndex === 3) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 280px;
        object-fit: cover;
      }
`;
    }

    // [4] container > columns-2 > col-0 > container
    if (elementIndex === 4) {
      css += `${selector} {
        display: flex;
        flex-direction: column;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [5] container > columns-2 > col-0 > container > text // "BEFORE"
    if (elementIndex === 5) {
      css += `${selector} {
        line-height: 1;
        letter-spacing: 2px;
      }
`;
    }

    // [6] container > columns-2 > col-0 > container > text // "Describe the problem, starting"
    if (elementIndex === 6) {
      css += `${selector} {
        line-height: 1.6;
      }
`;
    }

    // [7] container > columns-2 > col-1 > image
    if (elementIndex === 7) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 280px;
        object-fit: cover;
      }
`;
    }

    // [8] container > columns-2 > col-1 > container
    if (elementIndex === 8) {
      css += `${selector} {
        display: flex;
        flex-direction: column;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [9] container > columns-2 > col-1 > container > text // "AFTER"
    if (elementIndex === 9) {
      css += `${selector} {
        line-height: 1;
        letter-spacing: 2px;
      }
`;
    }

    // [10] container > columns-2 > col-1 > container > text // "Show the transformation, resul"
    if (elementIndex === 10) {
      css += `${selector} {
        line-height: 1.6;
      }
`;
    }

  return css;
};

const generate_bestsellers_row_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        flex-direction: column;
        background-color: #fafbfc;
        padding-top: 60px;
        padding-bottom: 60px;
        padding-left: 20px;
        padding-right: 20px;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > columns-2
    if (elementIndex === 1) {
      css += `${selector} {
        gap: 24px;
      }
`;
    }

    // [2] container > columns-2 > col-0 > heading // "Bestsellers"
    if (elementIndex === 2) {
      css += `${selector} {
        text-align: left;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 24px;
        }
      }
`;
    }

    // [3] container > columns-2 > col-1 > button // "View All"
    if (elementIndex === 3) {
      css += `${selector} {
        border-radius: 4px;
        cursor: pointer;
        display: block;
        padding-top: 10px;
        padding-right: 24px;
        padding-bottom: 10px;
        padding-left: 24px;
        border-width: 1px;
        border-style: solid;
      }
`;
    }

    // [4] container > columns-4
    if (elementIndex === 4) {
      css += `${selector} {
        gap: 24px;
      }
`;
    }

    // [5] container > columns-4 > col-0 > image
    if (elementIndex === 5) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 220px;
        object-fit: cover;
        border-radius: 6px;
        margin-top: 0;
        margin-bottom: 0;
      }
`;
    }

    // [6] container > columns-4 > col-0 > text // "BEST SELLER"
    if (elementIndex === 6) {
      css += `${selector} {
        letter-spacing: 1px;
        text-align: center;
      }
`;
    }

    // [7] container > columns-4 > col-0 > heading // "Product Name"
    if (elementIndex === 7) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [8] container > columns-4 > col-0 > text // "$49.00"
    if (elementIndex === 8) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [9] container > columns-4 > col-1 > image
    if (elementIndex === 9) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 220px;
        object-fit: cover;
        border-radius: 6px;
        margin-top: 0;
        margin-bottom: 0;
      }
`;
    }

    // [10] container > columns-4 > col-1 > text // "NEW"
    if (elementIndex === 10) {
      css += `${selector} {
        letter-spacing: 1px;
        text-align: center;
      }
`;
    }

    // [11] container > columns-4 > col-1 > heading // "Product Name"
    if (elementIndex === 11) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [12] container > columns-4 > col-1 > text // "$59.00"
    if (elementIndex === 12) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [13] container > columns-4 > col-2 > image
    if (elementIndex === 13) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 220px;
        object-fit: cover;
        border-radius: 6px;
        margin-top: 0;
        margin-bottom: 0;
      }
`;
    }

    // [14] container > columns-4 > col-2 > text // "POPULAR"
    if (elementIndex === 14) {
      css += `${selector} {
        letter-spacing: 1px;
        text-align: center;
      }
`;
    }

    // [15] container > columns-4 > col-2 > heading // "Product Name"
    if (elementIndex === 15) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [16] container > columns-4 > col-2 > text // "$39.00"
    if (elementIndex === 16) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [17] container > columns-4 > col-3 > image
    if (elementIndex === 17) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 220px;
        object-fit: cover;
        border-radius: 6px;
        margin-top: 0;
        margin-bottom: 0;
      }
`;
    }

    // [18] container > columns-4 > col-3 > text // "SALE"
    if (elementIndex === 18) {
      css += `${selector} {
        letter-spacing: 1px;
        text-align: center;
      }
`;
    }

    // [19] container > columns-4 > col-3 > heading // "Product Name"
    if (elementIndex === 19) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [20] container > columns-4 > col-3 > text // "$29.00"
    if (elementIndex === 20) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

  return css;
};

const generate_brand_story_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [2] container > columns-2 > col-0 > image
    if (elementIndex === 2) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
        min-height: 400px;
      }
`;
    }

    // [3] container > columns-2 > col-1 > container
    if (elementIndex === 3) {
      css += `${selector} {
        display: flex;
        flex-direction: column;
        justify-content: center;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
          padding-left: 16px;
          padding-right: 16px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [4] container > columns-2 > col-1 > container > text // "OUR STORY"
    if (elementIndex === 4) {
      css += `${selector} {
        line-height: 1;
        letter-spacing: 2px;
      }
`;
    }

    // [5] container > columns-2 > col-1 > container > heading // "Built with Purpose"
    if (elementIndex === 5) {
      css += `${selector} {
        line-height: 1.2;
        text-align: left;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 24px;
        }
      }
`;
    }

    // [6] container > columns-2 > col-1 > container > text // "We started with a simple belie"
    if (elementIndex === 6) {
      css += `${selector} {
        line-height: 1.8;
      }
`;
    }

    // [7] container > columns-2 > col-1 > container > text // "Our commitment goes beyond pro"
    if (elementIndex === 7) {
      css += `${selector} {
        line-height: 1.8;
      }
`;
    }

    // [8] container > columns-2 > col-1 > container > button // "Learn More About Us"
    if (elementIndex === 8) {
      css += `${selector} {
        border-radius: 4px;
        cursor: pointer;
        display: inline-block;
        padding-top: 12px;
        padding-right: 28px;
        padding-bottom: 12px;
        padding-left: 28px;
        border-width: 1px;
        border-style: solid;
      }
`;
    }

  return css;
};

const generate_content_fullwidth_text_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
          padding-left: 16px;
          padding-right: 16px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > heading // "Our Mission"
    if (elementIndex === 1) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [2] container > text // "We believe in building tools t"
    if (elementIndex === 2) {
      css += `${selector} {
        line-height: 1.8;
        text-align: center;
      }
`;
    }

  return css;
};

const generate_content_stats_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        padding-top: 40px;
        padding-bottom: 40px;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 20px;
          padding-bottom: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 28px;
          padding-bottom: 28px;
        }
      }
`;
    }

    // [1] container > columns-4
    if (elementIndex === 1) {
    }

    // [2] container > columns-4 > col-0 > heading // "10K+"
    if (elementIndex === 2) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [3] container > columns-4 > col-0 > text // "Customers"
    if (elementIndex === 3) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [4] container > columns-4 > col-1 > heading // "99.9%"
    if (elementIndex === 4) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [5] container > columns-4 > col-1 > text // "Uptime"
    if (elementIndex === 5) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [6] container > columns-4 > col-2 > heading // "50M+"
    if (elementIndex === 6) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [7] container > columns-4 > col-2 > text // "Page Views"
    if (elementIndex === 7) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [8] container > columns-4 > col-3 > heading // "24/7"
    if (elementIndex === 8) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [9] container > columns-4 > col-3 > text // "Support"
    if (elementIndex === 9) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

  return css;
};

const generate_content_text_image_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [2] container > columns-2 > col-0 > container
    if (elementIndex === 2) {
      css += `${selector} {
        display: flex;
        flex-direction: column;
        justify-content: center;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        padding-left: 40px;
        padding-right: 40px;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-left: 16px;
          padding-right: 16px;
        }
      }
`;
    }

    // [3] container > columns-2 > col-0 > container > heading // "About Our Story"
    if (elementIndex === 3) {
      css += `${selector} {
        text-align: left;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 24px;
        }
      }
`;
    }

    // [4] container > columns-2 > col-0 > container > text // "Share your story with the worl"
    if (elementIndex === 4) {
      css += `${selector} {
        line-height: 1.8;
      }
`;
    }

    // [5] container > columns-2 > col-1 > image
    if (elementIndex === 5) {
      css += `${selector} {
        width: 100%;
        height: 100%;
        object-fit: cover;
        min-height: 300px;
      }
`;
    }

  return css;
};

const generate_countdown_sale_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        max-width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        padding-left: 20px;
        padding-right: 20px;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 20px;
          padding-bottom: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 28px;
          padding-bottom: 28px;
        }
      }
`;
    }

    // [1] container > text // "LIMITED TIME OFFER"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1;
        display: block;
        letter-spacing: 3px;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [2] container > heading // "Flash Sale - Up to 50% Off"
    if (elementIndex === 2) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [3] container > countdown
    if (elementIndex === 3) {
      css += `${selector} {
        margin-right: 0;
        margin-bottom: 0;
        margin-left: 0;
      }
`;
    }

    // [4] container > button // "Shop the Sale"
    if (elementIndex === 4) {
      css += `${selector} {
        border-radius: 6px;
        cursor: pointer;
        display: inline-block;
        padding-top: 14px;
        padding-right: 40px;
        padding-bottom: 14px;
        padding-left: 40px;
        border-width: 1px;
        border-style: solid;
      }
`;
    }

  return css;
};

const generate_cta_banner_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > heading // "Ready to Get Started?"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1.2;
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
    }

    // [2] container > text // "Join thousands of satisfied cu"
    if (elementIndex === 2) {
      css += `${selector} {
        line-height: 1.6;
        max-width: 500px;
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 14px;
        }
      }
`;
    }

    // [3] container > button // "Start Free Trial"
    if (elementIndex === 3) {
      css += `${selector} {
        border-radius: 6px;
        cursor: pointer;
        display: inline-block;
        border-width: 1px;
        border-style: solid;
      }
`;
    }

  return css;
};

const generate_cta_minimal_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          flex-direction: column;
          text-align: center;
          padding-top: 28px;
          padding-bottom: 28px;
        }
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 20px;
          padding-bottom: 20px;
        }
      }
`;
    }

    // [1] container > text // "Ready to start building?"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1;
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 14px;
        }
      }
`;
    }

    // [2] container > button // "Get Started"
    if (elementIndex === 2) {
      css += `${selector} {
        border-radius: 4px;
        cursor: pointer;
        display: inline-block;
        border-width: 1px;
        border-style: solid;
      }
`;
    }

  return css;
};

const generate_cta_split_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        background-color: #f6f8fa;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [1] container > columns-2
    if (elementIndex === 1) {
    }

    // [2] container > columns-2 > col-0 > container
    if (elementIndex === 2) {
      css += `${selector} {
        display: flex;
        flex-direction: column;
        justify-content: center;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [3] container > columns-2 > col-0 > container > heading // "Don't Miss Out"
    if (elementIndex === 3) {
      css += `${selector} {
        line-height: 1.2;
        text-align: left;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
    }

    // [4] container > columns-2 > col-0 > container > text // "Sign up today and get exclusiv"
    if (elementIndex === 4) {
      css += `${selector} {
        line-height: 1.6;
        text-align: left;
      }
`;
    }

    // [5] container > columns-2 > col-1 > container
    if (elementIndex === 5) {
      css += `${selector} {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [6] container > columns-2 > col-1 > container > button // "Sign Up Now"
    if (elementIndex === 6) {
      css += `${selector} {
        border-radius: 6px;
        cursor: pointer;
        display: inline-block;
        border-width: 1px;
        border-style: solid;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 14px;
          padding-left: 24px;
          padding-right: 24px;
        }
      }
`;
    }

  return css;
};

const generate_features_3col_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        flex-direction: column;
        align-items: center;
        padding-left: 20px;
        padding-right: 20px;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > heading // "Why Choose Us"
    if (elementIndex === 1) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [3] container > columns-3 > col-0 > icon
    if (elementIndex === 3) {
      css += `${selector} {
        display: inline-block;
        margin-right: auto;
        margin-left: auto;
      }
`;
    }

    // [4] container > columns-3 > col-0 > heading // "Fast Performance"
    if (elementIndex === 4) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [5] container > columns-3 > col-0 > text // "Lightning-fast load times that"
    if (elementIndex === 5) {
      css += `${selector} {
        line-height: 1.6;
        text-align: center;
      }
`;
    }

    // [6] container > columns-3 > col-1 > icon
    if (elementIndex === 6) {
      css += `${selector} {
        display: inline-block;
        margin-right: auto;
        margin-left: auto;
      }
`;
    }

    // [7] container > columns-3 > col-1 > heading // "Easy to Use"
    if (elementIndex === 7) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [8] container > columns-3 > col-1 > text // "Intuitive interface designed f"
    if (elementIndex === 8) {
      css += `${selector} {
        line-height: 1.6;
        text-align: center;
      }
`;
    }

    // [9] container > columns-3 > col-2 > icon
    if (elementIndex === 9) {
      css += `${selector} {
        display: inline-block;
        margin-right: auto;
        margin-left: auto;
      }
`;
    }

    // [10] container > columns-3 > col-2 > heading // "Fully Responsive"
    if (elementIndex === 10) {
      css += `${selector} {
        text-align: center;
      }
`;
    }

    // [11] container > columns-3 > col-2 > text // "Looks perfect on every device,"
    if (elementIndex === 11) {
      css += `${selector} {
        line-height: 1.6;
        text-align: center;
      }
`;
    }

  return css;
};

const generate_features_alternating_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        flex-direction: column;
        gap: 40px;
        padding-left: 20px;
        padding-right: 20px;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [2] container > columns-2 > col-0 > image
    if (elementIndex === 2) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 300px;
        object-fit: cover;
        border-radius: 8px;
      }
`;
    }

    // [3] container > columns-2 > col-1 > heading // "Feature One"
    if (elementIndex === 3) {
      css += `${selector} {
        text-align: left;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
    }

    // [4] container > columns-2 > col-1 > text // "Explain this feature in detail"
    if (elementIndex === 4) {
      css += `${selector} {
        line-height: 1.6;
        text-align: left;
      }
`;
    }

    // [6] container > columns-2 > col-0 > heading // "Feature Two"
    if (elementIndex === 6) {
      css += `${selector} {
        text-align: left;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
    }

    // [7] container > columns-2 > col-0 > text // "Describe the second feature. P"
    if (elementIndex === 7) {
      css += `${selector} {
        line-height: 1.6;
        text-align: left;
      }
`;
    }

    // [8] container > columns-2 > col-1 > image
    if (elementIndex === 8) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 300px;
        object-fit: cover;
        border-radius: 8px;
      }
`;
    }

  return css;
};

const generate_hero_centered_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        max-width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-align: center;
        padding-left: 20px;
        padding-right: 20px;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 40px;
          padding-bottom: 40px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 56px;
          padding-bottom: 56px;
        }
      }
`;
    }

    // [1] container > heading // "Your Bold Headline Here"
    if (elementIndex === 1) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 36px;
        }
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 28px;
        }
      }
`;
    }

    // [2] container > text // "A compelling subtitle that sup"
    if (elementIndex === 2) {
      css += `${selector} {
        line-height: 1.6;
        display: block;
        max-width: 600px;
        text-align: center;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 16px;
        }
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 14px;
        }
      }
`;
    }

    // [3] container > button // "Get Started"
    if (elementIndex === 3) {
      css += `${selector} {
        border-radius: 6px;
        cursor: pointer;
        display: inline-block;
        padding-top: 16px;
        padding-right: 40px;
        padding-bottom: 16px;
        padding-left: 40px;
        border-width: 1px;
        border-style: solid;
      }
`;
      css += `${selector}:hover {
        border-width: 1px;
        border-style: solid;
      }
`;
    }

  return css;
};

const generate_hero_image_bg_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] image-background
    if (elementIndex === 0) {
      css += `${selector} {
        position: relative;
        min-height: 500px;
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        background-color: #1a1a1a;
        padding-left: 20px;
        padding-right: 20px;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [1] image-background > container
    if (elementIndex === 1) {
      css += `${selector} {
        display: flex;
        flex-direction: column;
        justify-content: center;
        width: 100%;
        height: 100%;
        max-width: 100%;
        box-sizing: border-box;
        overflow: visible;
        flex: 1;
        padding-top: 0;
        padding-bottom: 0;
        padding-left: 0;
        padding-right: 0;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [2] image-background > container > heading // "Immersive Experience"
    if (elementIndex === 2) {
      css += `${selector} {
        text-align: center;
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 36px;
        }
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 28px;
        }
      }
`;
    }

    // [3] image-background > container > text // "Create stunning visual experie"
    if (elementIndex === 3) {
      css += `${selector} {
        line-height: 1.6;
        text-align: center;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 14px;
        }
      }
`;
    }

    // [4] image-background > container > button // "Explore"
    if (elementIndex === 4) {
      css += `${selector} {
        border-radius: 6px;
        cursor: pointer;
        display: inline-block;
        padding-top: 16px;
        padding-right: 40px;
        padding-bottom: 16px;
        padding-left: 40px;
        border-width: 1px;
        border-style: solid;
      }
`;
      css += `${selector}:hover {
        border-width: 1px;
        border-style: solid;
      }
`;
    }

  return css;
};

const generate_hero_split_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        max-width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [1] container > columns-2
    if (elementIndex === 1) {
      css += `${selector} {
        gap: 24px;
        align-items: stretch;
      }
`;
      const col0Selector = `#${sectionId}-{{ section.id }} [data-element-id="${element.id}-col-0"]`;
      css += `${col0Selector} {
        justify-content: center;
        align-items: flex-start;
        background-color: #ffffff;
        padding-top: 60px;
        padding-bottom: 60px;
        padding-left: 40px;
        padding-right: 40px;
      }
`;
    }

    // [2] container > columns-2 > col-0 > heading // "Build Something Amazing"
    if (elementIndex === 2) {
      css += `${selector} {
        line-height: 1.2;
        display: block;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 32px;
        }
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 25px;
        }
      }
`;
    }

    // [3] container > columns-2 > col-0 > text // "Describe your product or servi"
    if (elementIndex === 3) {
      css += `${selector} {
        line-height: 1.6;
        display: block;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [4] container > columns-2 > col-0 > button // "Learn More"
    if (elementIndex === 4) {
      css += `${selector} {
        border-radius: 6px;
        cursor: pointer;
        display: inline-block;
        padding-top: 14px;
        padding-right: 32px;
        padding-bottom: 14px;
        padding-left: 32px;
        border-width: 1px;
        border-style: solid;
      }
`;
      css += `${selector}:hover {
        border-width: 1px;
        border-style: solid;
      }
`;
    }

    // [5] container > columns-2 > col-1 > image
    if (elementIndex === 5) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
        margin-top: 0;
        margin-right: 0;
        margin-bottom: 0;
        margin-left: 0;
      }
`;
    }

  return css;
};

const generate_image_gallery_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > heading // "The Lookbook"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1.2;
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [2] container > columns-3
    if (elementIndex === 2) {
      // Hardcode column styles — all 3 columns get align-items: stretch
      for (let i = 0; i < 3; i++) {
        const colSelector = selector.replace(element.id, `${element.id}-col-${i}`);
        css += `${colSelector} {
      align-items: stretch;
    }
`;
      }
    }

    // [3] container > columns-3 > col-0 > image
    if (elementIndex === 3) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 300px;
        object-fit: cover;
        border-radius: 4px;
      }
`;
    }

    // [4] container > columns-3 > col-0 > image
    if (elementIndex === 4) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 200px;
        object-fit: cover;
        border-radius: 4px;
      }
`;
    }

    // [5] container > columns-3 > col-1 > image
    if (elementIndex === 5) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 200px;
        object-fit: cover;
        border-radius: 4px;
      }
`;
    }

    // [6] container > columns-3 > col-1 > image
    if (elementIndex === 6) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 300px;
        object-fit: cover;
        border-radius: 4px;
      }
`;
    }

    // [7] container > columns-3 > col-2 > image
    if (elementIndex === 7) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 300px;
        object-fit: cover;
        border-radius: 4px;
      }
`;
    }

    // [8] container > columns-3 > col-2 > image
    if (elementIndex === 8) {
      css += `${selector} {
        display: block;
        width: 100%;
        height: 200px;
        object-fit: cover;
        border-radius: 4px;
      }
`;
    }

  return css;
};

const generate_instagram_feed_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: #fafbfc;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > text // "#YOURBRAND"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1;
        letter-spacing: 2px;
        text-align: center;
      }
`;
    }

    // [2] container > heading // "Share Your Style"
    if (elementIndex === 2) {
      css += `${selector} {
        line-height: 1.2;
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 24px;
        }
      }
`;
    }

    // [3] container > columns-6
    if (elementIndex === 3) {
      // Hardcode column styles — all 6 columns get align-items: center
      for (let i = 0; i < 6; i++) {
        const colSelector = selector.replace(element.id, `${element.id}-col-${i}`);
        css += `${colSelector} {
      align-items: center;
    }
`;
      }
    }

    // [4] container > columns-6 > col-0 > image
    if (elementIndex === 4) {
      css += `${selector} {
        display: block;
        width: 160px;
        height: 160px;
        object-fit: cover;
      }
`;
    }

    // [5] container > columns-6 > col-1 > image
    if (elementIndex === 5) {
      css += `${selector} {
        display: block;
        width: 160px;
        height: 160px;
        object-fit: cover;
      }
`;
    }

    // [6] container > columns-6 > col-2 > image
    if (elementIndex === 6) {
      css += `${selector} {
        display: block;
        width: 160px;
        height: 160px;
        object-fit: cover;
      }
`;
    }

    // [7] container > columns-6 > col-3 > image
    if (elementIndex === 7) {
      css += `${selector} {
        display: block;
        width: 160px;
        height: 160px;
        object-fit: cover;
      }
`;
    }

    // [8] container > columns-6 > col-4 > image
    if (elementIndex === 8) {
      css += `${selector} {
        display: block;
        width: 160px;
        height: 160px;
        object-fit: cover;
      }
`;
    }

    // [9] container > columns-6 > col-5 > image
    if (elementIndex === 9) {
      css += `${selector} {
        display: block;
        width: 160px;
        height: 160px;
        object-fit: cover;
      }
`;
    }

  return css;
};

const generate_logo_banner_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        max-width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 20px;
        padding-left: 20px;
        padding-right: 20px;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [1] container > text // "AS FEATURED IN"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1;
        display: block;
        letter-spacing: 2px;
        text-align: center;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [2] container > columns-5
    if (elementIndex === 2) {
      css += `${selector} {
        gap: 24px;
        align-items: stretch;
        justify-content: flex-start;
      }
`;
      // Hardcode column styles — all 5 columns get align-items: center
      for (let i = 0; i < 5; i++) {
        const colSelector = selector.replace(element.id, `${element.id}-col-${i}`);
        css += `${colSelector} {
        align-items: center;
      }
`;
      }
    }

    // [3] container > columns-5 > col-0 > image
    if (elementIndex === 3) {
      css += `${selector} {
        display: block;
        width: 120px;
        height: 40px;
        object-fit: contain;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [4] container > columns-5 > col-1 > image
    if (elementIndex === 4) {
      css += `${selector} {
        display: block;
        width: 120px;
        height: 40px;
        object-fit: contain;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [5] container > columns-5 > col-2 > image
    if (elementIndex === 5) {
      css += `${selector} {
        display: block;
        width: 120px;
        height: 40px;
        object-fit: contain;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [6] container > columns-5 > col-3 > image
    if (elementIndex === 6) {
      css += `${selector} {
        display: block;
        width: 120px;
        height: 40px;
        object-fit: contain;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [7] container > columns-5 > col-4 > image
    if (elementIndex === 7) {
      css += `${selector} {
        display: block;
        width: 120px;
        height: 40px;
        object-fit: contain;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

  return css;
};

const generate_multi_column_text_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        border-width: 0px;
        border-style: none;
      }
`;
    }

    // [1] container > heading // "Our Values"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1.2;
        text-align: center;
      }
`;
    }

    // [2] container > columns-3
    if (elementIndex === 2) {
      // Hardcode column styles — all 3 columns get align-items: flex-start
      for (let i = 0; i < 3; i++) {
        const colSelector = selector.replace(element.id, `${element.id}-col-${i}`);
        css += `${colSelector} {
      align-items: flex-start;
    }
`;
      }
    }

    // [3] container > columns-3 > col-0 > heading // "Sustainability"
    if (elementIndex === 3) {
      css += `${selector} {
        line-height: 1.2;
        text-align: left;
      }
`;
    }

    // [4] container > columns-3 > col-0 > divider
    if (elementIndex === 4) {
      css += `${selector} {
        margin-left: 0;
        margin-right: 0;
      }
`;
    }

    // [5] container > columns-3 > col-0 > text // "We source materials responsibl"
    if (elementIndex === 5) {
      css += `${selector} {
        line-height: 1.8;
      }
`;
    }

    // [6] container > columns-3 > col-1 > heading // "Quality"
    if (elementIndex === 6) {
      css += `${selector} {
        line-height: 1.2;
        text-align: left;
      }
`;
    }

    // [7] container > columns-3 > col-1 > divider
    if (elementIndex === 7) {
      css += `${selector} {
        margin-left: 0;
        margin-right: 0;
      }
`;
    }

    // [8] container > columns-3 > col-1 > text // "Each product undergoes rigorou"
    if (elementIndex === 8) {
      css += `${selector} {
        line-height: 1.8;
      }
`;
    }

    // [9] container > columns-3 > col-2 > heading // "Community"
    if (elementIndex === 9) {
      css += `${selector} {
        line-height: 1.2;
        text-align: left;
      }
`;
    }

    // [10] container > columns-3 > col-2 > divider
    if (elementIndex === 10) {
      css += `${selector} {
        margin-left: 0;
        margin-right: 0;
      }
`;
    }

    // [11] container > columns-3 > col-2 > text // "We believe in giving back. A p"
    if (elementIndex === 11) {
      css += `${selector} {
        line-height: 1.8;
      }
`;
    }

  return css;
};

const generate_product_card_grid_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

  // [0] container
  if (elementIndex === 0) {
    css += `${selector} {
      flex-direction: column;
      padding-left: 20px;
      padding-right: 20px;
    }
`;
  }

  // [2] columns-3 — hardcode column styles
  if (elementIndex === 2) {
    for (let i = 0; i < 3; i++) {
      const colSelector = selector.replace(element.id, `${element.id}-col-${i}`);
      css += `${colSelector} {
      align-items: center;
      border-radius: 8px;
      overflow: hidden;
      background-color: #ffffff;
    }
`;
    }
  }

  // [3] col-0 > image, [7] col-1 > image, [11] col-2 > image
  if (elementIndex === 3 || elementIndex === 7 || elementIndex === 11) {
    css += `${selector} {
      object-fit: cover;
    }
`;
  }

  // [6] col-0 > button, [10] col-1 > button, [14] col-2 > button
  if (elementIndex === 6 || elementIndex === 10 || elementIndex === 14) {
    css += `${selector} {
      padding-top: 5px;
      padding-bottom: 5px;
      padding-left: 5px;
      padding-right: 5px;
      border-radius: 6px;
      border-width: 1px;
      border-style: solid;
    }
${selector}:hover {
      border-width: 1px;
      border-style: solid;
    }
`;
  }

  return css;
};

const generate_shipping_guarantee_bar_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        max-width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        padding-top: 24px;
        padding-bottom: 24px;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [1] container > columns-4
    if (elementIndex === 1) {
      css += `${selector} {
        gap: 24px;
        align-items: stretch;
        justify-content: flex-start;
      }
`;
      // Hardcode columns-4 col-0 through col-3
      for (let i = 0; i < 4; i++) {
        const colSelector = selector.replace(element.id, `${element.id}-col-${i}`);
        css += `${colSelector} {
        align-items: center;
      }
`;
      }
    }

    // [2] columns-4 > col-0 > icon
    if (elementIndex === 2) {
      css += `${selector} {
        display: inline-block;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [3] columns-4 > col-0 > heading // "Free Shipping"
    if (elementIndex === 3) {
      css += `${selector} {
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [4] columns-4 > col-0 > text // "On orders over $50"
    if (elementIndex === 4) {
      css += `${selector} {
        line-height: 1.3;
        display: block;
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [5] columns-4 > col-1 > icon
    if (elementIndex === 5) {
      css += `${selector} {
        display: inline-block;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [6] columns-4 > col-1 > heading // "Easy Returns"
    if (elementIndex === 6) {
      css += `${selector} {
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [7] columns-4 > col-1 > text // "30-day money back"
    if (elementIndex === 7) {
      css += `${selector} {
        line-height: 1.3;
        display: block;
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [8] columns-4 > col-2 > icon
    if (elementIndex === 8) {
      css += `${selector} {
        display: inline-block;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [9] columns-4 > col-2 > heading // "Secure Checkout"
    if (elementIndex === 9) {
      css += `${selector} {
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [10] columns-4 > col-2 > text // "SSL encrypted payment"
    if (elementIndex === 10) {
      css += `${selector} {
        line-height: 1.3;
        display: block;
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [11] columns-4 > col-3 > icon
    if (elementIndex === 11) {
      css += `${selector} {
        display: inline-block;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
      }
`;
    }

    // [12] columns-4 > col-3 > heading // "24/7 Support"
    if (elementIndex === 12) {
      css += `${selector} {
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

    // [13] columns-4 > col-3 > text // "Chat with us anytime"
    if (elementIndex === 13) {
      css += `${selector} {
        line-height: 1.3;
        display: block;
        text-align: center;
        padding-top: 0;
        padding-bottom: 0;
        padding-right: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

  return css;
};

const generate_testimonial_spotlight_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 40px;
          padding-bottom: 40px;
          padding-left: 16px;
          padding-right: 16px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 56px;
          padding-bottom: 56px;
        }
      }
`;
    }

    // [1] container > text // ""This is the single best tool "
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1.8;
        font-style: italic;
        max-width: 700px;
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 20px;
        }
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 19px;
        }
      }
`;
    }

    // [2] container > text // "Alex Turner"
    if (elementIndex === 2) {
    }

    // [3] container > text // "VP of Engineering, GlobalTech"
    if (elementIndex === 3) {
      css += `${selector} {
        line-height: 1;
        display: block;
        padding-top: 6px;
        padding-right: 0;
        padding-bottom: 0;
        padding-left: 0;
        margin-right: 0;
        margin-left: 0;
      }
`;
    }

  return css;
};

const generate_testimonials_cards_CSS = (element, elementDef, selector, sectionId) => {
  let css = '';
  const elementIndex = getElementIndex(element);

    // [0] container
    if (elementIndex === 0) {
      css += `${selector} {
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: #fafbfc;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-top: 30px;
          padding-bottom: 30px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          padding-top: 42px;
          padding-bottom: 42px;
        }
      }
`;
    }

    // [1] container > heading // "What Our Customers Say"
    if (elementIndex === 1) {
      css += `${selector} {
        line-height: 1.2;
        text-align: center;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          font-size: 22px;
        }
      }
`;
      css += `@media (min-width: 576px) and (max-width: 767px) {
        ${selector} {
          font-size: 27px;
        }
      }
`;
    }

    // [2] container > columns-3
    if (elementIndex === 2) {
      // Hardcode column styles — all 3 columns get align-items: stretch
      for (let i = 0; i < 3; i++) {
        const colSelector = selector.replace(element.id, `${element.id}-col-${i}`);
        css += `${colSelector} {
      align-items: stretch;
    }
`;
      }
    }

    // [3] container > columns-3 > col-0 > container
    if (elementIndex === 3) {
      css += `${selector} {
        background-color: #ffffff;
        border-radius: 8px;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-left: 12px;
          padding-right: 12px;
        }
      }
`;
    }

    // [4] container > columns-3 > col-0 > container > text // ""This product completely trans"
    if (elementIndex === 4) {
      css += `${selector} {
        line-height: 1.6;
        font-style: italic;
      }
`;
    }

    // [5] container > columns-3 > col-0 > container > text // "Sarah Johnson"
    if (elementIndex === 5) {
      css += `${selector} {
        line-height: 1;
      }
`;
    }

    // [6] container > columns-3 > col-0 > container > text // "CEO, TechCorp"
    if (elementIndex === 6) {
      css += `${selector} {
        line-height: 1;
      }
`;
    }

    // [7] container > columns-3 > col-1 > container
    if (elementIndex === 7) {
      css += `${selector} {
        background-color: #ffffff;
        border-radius: 8px;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-left: 12px;
          padding-right: 12px;
        }
      }
`;
    }

    // [8] container > columns-3 > col-1 > container > text // ""Incredible quality and attent"
    if (elementIndex === 8) {
      css += `${selector} {
        line-height: 1.6;
        font-style: italic;
      }
`;
    }

    // [9] container > columns-3 > col-1 > container > text // "Mike Chen"
    if (elementIndex === 9) {
      css += `${selector} {
        line-height: 1;
      }
`;
    }

    // [10] container > columns-3 > col-1 > container > text // "Founder, StartupXYZ"
    if (elementIndex === 10) {
      css += `${selector} {
        line-height: 1;
      }
`;
    }

    // [11] container > columns-3 > col-2 > container
    if (elementIndex === 11) {
      css += `${selector} {
        background-color: #ffffff;
        border-radius: 8px;
        height: 100%;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        flex: 1;
        display: flex;
        flex-direction: column;
        margin-top: 0;
        margin-bottom: 0;
        margin-right: 0;
        margin-left: 0;
        align-items: flex-start;
        border-width: 0px;
        border-style: none;
      }
`;
      css += `@media (max-width: 575px) {
        ${selector} {
          padding-left: 12px;
          padding-right: 12px;
        }
      }
`;
    }

    // [12] container > columns-3 > col-2 > container > text // ""The best investment we've mad"
    if (elementIndex === 12) {
      css += `${selector} {
        line-height: 1.6;
        font-style: italic;
      }
`;
    }

    // [13] container > columns-3 > col-2 > container > text // "Emily Roberts"
    if (elementIndex === 13) {
      css += `${selector} {
        line-height: 1;
      }
`;
    }

    // [14] container > columns-3 > col-2 > container > text // "Director, MediaGroup"
    if (elementIndex === 14) {
      css += `${selector} {
        line-height: 1;
      }
`;
    }

  return css;
};

/**
 * Template CSS generators registry.
 */
export const templateCSSGenerators = {
  'announcement-bar': generate_announcement_bar_CSS,
  'before-after': generate_before_after_CSS,
  'bestsellers-row': generate_bestsellers_row_CSS,
  'brand-story': generate_brand_story_CSS,
  'content-fullwidth-text': generate_content_fullwidth_text_CSS,
  'content-stats': generate_content_stats_CSS,
  'content-text-image': generate_content_text_image_CSS,
  'countdown-sale': generate_countdown_sale_CSS,
  'cta-banner': generate_cta_banner_CSS,
  'cta-minimal': generate_cta_minimal_CSS,
  'cta-split': generate_cta_split_CSS,
  'features-3col': generate_features_3col_CSS,
  'features-alternating': generate_features_alternating_CSS,
  'hero-centered': generate_hero_centered_CSS,
  'hero-image-bg': generate_hero_image_bg_CSS,
  'hero-split': generate_hero_split_CSS,
  'image-gallery': generate_image_gallery_CSS,
  'instagram-feed': generate_instagram_feed_CSS,
  'logo-banner': generate_logo_banner_CSS,
  'multi-column-text': generate_multi_column_text_CSS,
  'product-card-grid': generate_product_card_grid_CSS,
  'shipping-guarantee-bar': generate_shipping_guarantee_bar_CSS,
  'testimonial-spotlight': generate_testimonial_spotlight_CSS,
  'testimonials-cards': generate_testimonials_cards_CSS,
};
